matrix:
  fast_finish: true
  include:
  - os: linux
    sudo: false
    language: python
    python: '3.7'
    dist: xenial

install:
  - pip install .

script:
  - conan-package-updater bincrafters ${GITHUB_TOKEN} --ignore --dry-run --ignore-pattern="conan-boost*"
