build: false


environment:
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.8"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          PYTHON: "C:\\Python37"
          PYTHON_VERSION: "3.7.0"


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install .

test_script:
- conan-package-updater bincrafters ${GITHUB_TOKEN} --ignore --dry-run
- python setup.py install
